
package fawda.java.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.1 2018-05-29T10:34:21.483+08:00
 * Generated source version: 3.2.1
 * @author liuyl@risen.com 2018年5月29日12:09:01
 */
public final class EdocWebServicePortTypeClient {

    private static final QName SERVICE_NAME = new QName("http://webservice.wellhope.com", "EdocWebService");

    private EdocWebServicePortTypeClient() {
        
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EdocWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EdocWebService ss = new EdocWebService(wsdlURL, SERVICE_NAME);
        EdocWebServicePortType port = ss.getEdocWebServiceHttpPort();

        {
            System.out.println("Invoking formInfoSend...");
            String _formInfoSend_in0 = "";
            String _formInfoSend_in1 = "";
            String _formInfoSend_in2 = "";
            String _formInfoSend_in3 = "";
            String _formInfoSend__return = port.formInfoSend(_formInfoSend_in0, _formInfoSend_in1, _formInfoSend_in2, _formInfoSend_in3);
            System.out.println("formInfoSend.result=" + _formInfoSend__return);
        }
        {
            System.out.println("Invoking singleFileSend...");
            String _singleFileSend_in0 = "";
            String _singleFileSend_in1 = "";
            String _singleFileSend_in2 = "";
            int _singleFileSend_in3 = 0;
            String _singleFileSend_in4 = "";
            String _singleFileSend_in5 = "";
            int _singleFileSend_in6 = 0;
            String _singleFileSend_in7 = "";
            String _singleFileSend_in8 = "";
            String _singleFileSend_in9 = "";
            String _singleFileSend_in10 = "";
            String _singleFileSend_in11 = "";
            String _singleFileSend__return = port.singleFileSend(_singleFileSend_in0, _singleFileSend_in1, _singleFileSend_in2,
                    _singleFileSend_in3, _singleFileSend_in4, _singleFileSend_in5, _singleFileSend_in6, _singleFileSend_in7, _singleFileSend_in8,
                    _singleFileSend_in9, _singleFileSend_in10, _singleFileSend_in11);
            System.out.println("singleFileSend.result=" + _singleFileSend__return);
        }
        System.exit(0);
    }

}
