package fawda.java.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-05-29T10:34:21.593+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://webservice.wellhope.com", name = "EdocWebServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface EdocWebServicePortType {

    @WebMethod
    @RequestWrapper(localName = "formInfoSend", targetNamespace = "http://webservice.wellhope.com", className = "com.risen.wh.webservice.FormInfoSend")
    @ResponseWrapper(localName = "formInfoSendResponse", targetNamespace = "http://webservice.wellhope.com", className = "com.risen.wh.webservice.FormInfoSendResponse")
    @WebResult(name = "out", targetNamespace = "http://webservice.wellhope.com")
    public String formInfoSend(
        @WebParam(name = "in0", targetNamespace = "http://webservice.wellhope.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.wellhope.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.wellhope.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.wellhope.com")
        String in3
    );

    @WebMethod
    @RequestWrapper(localName = "singleFileSend", targetNamespace = "http://webservice.wellhope.com", className = "com.risen.wh.webservice.SingleFileSend")
    @ResponseWrapper(localName = "singleFileSendResponse", targetNamespace = "http://webservice.wellhope.com", className = "com.risen.wh.webservice.SingleFileSendResponse")
    @WebResult(name = "out", targetNamespace = "http://webservice.wellhope.com")
    public String singleFileSend(
        @WebParam(name = "in0", targetNamespace = "http://webservice.wellhope.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.wellhope.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.wellhope.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.wellhope.com")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.wellhope.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://webservice.wellhope.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://webservice.wellhope.com")
        int in6,
        @WebParam(name = "in7", targetNamespace = "http://webservice.wellhope.com")
        String in7,
        @WebParam(name = "in8", targetNamespace = "http://webservice.wellhope.com")
        String in8,
        @WebParam(name = "in9", targetNamespace = "http://webservice.wellhope.com")
        String in9,
        @WebParam(name = "in10", targetNamespace = "http://webservice.wellhope.com")
        String in10,
        @WebParam(name = "in11", targetNamespace = "http://webservice.wellhope.com")
        String in11
    );
}
